name: Maven Publish

on:
  push:
    branches: [master]

jobs:
  publish:
    name: Publish to Maven
    strategy:
      matrix:
        arch: [ubuntu-latest]
        git-version: ["2.41.0 "]
    runs-on: ${{ matrix.arch }}

    # Steps
    steps:
      # Checkout the repo
      - name: Checkout
        uses: https://github.com/actions/checkout@v2

      # Set up JDK 8
      - name: Set up JDK
        uses: https://github.com/actions/setup-java@v3.12.0
        with:
          distribution: zulu
          java-version: 8

      # Setup Maven
      - name: Set up Maven
        uses: https://github.com/stCarolas/setup-maven@v4.5
        with:
          maven-version: 3.9.4

      # Configure Maven settings
      - name: Maven Settings
        uses: https://github.com/s4u/maven-settings-action@v2.8.0
        with:
          servers: |
            [
              {
                "id": "rainnny-repo-public",
                "username": "${{ secrets.PRIVATE_MAVEN_USER }}",
                "password": "${{ secrets.PRIVATE_MAVEN_PASS }}"
              }
            ]

      # Publish to Maven
      - name: Publish to Maven
        run: mvn deploy -B -Dstyle.color=always --update-snapshots